# ============================================================================
# Genomic Variant Classifier — multi-stage Dockerfile
# ============================================================================
#
# Stage 1: builder
#   - Installs all dependencies (including heavy training deps)
#   - Produces a virtualenv at /opt/venv
#
# Stage 2: api  (default target)
#   - Copies only the inference virtualenv and src/api + src/models
#   - No PySpark, no TensorFlow unless NNs are included
#   - ~1.2 GB final image
#
# Stage 3: trainer  (optional, build with --target trainer)
#   - Includes PySpark, XGBoost, LightGBM, and all data connectors
#   - Used for periodic re-training jobs; not deployed as a service
#
# Usage
# -----
#   # Build the API image (default)
#   docker build -t genomic-variant-api:phase2-v1 .
#
#   # Build the trainer image
#   docker build --target trainer -t genomic-variant-trainer:phase2-v1 .
#
#   # Run the API locally
#   docker run -p 8000:8000 \
#       -e MODEL_PATH=/app/models/phase2_pipeline.joblib \
#       -v $(pwd)/models:/app/models:ro \
#       genomic-variant-api:phase2-v1
#
# Environment variables (API container)
# --------------------------------------
#   MODEL_PATH           Path to serialised InferencePipeline joblib
#                        (default: /app/models/phase2_pipeline.joblib)
#   GNOMAD_INDEX_PATH    Optional gnomAD parquet for live AF lookup
#   LOG_LEVEL            INFO (default) | DEBUG | WARNING
#   WORKERS              Number of gunicorn workers (default: 2)
# ============================================================================

ARG PYTHON_VERSION=3.11
ARG DEBIAN_FRONTEND=noninteractive


# ----------------------------------------------------------------------------
# Stage 1 — dependency builder
# ----------------------------------------------------------------------------
FROM python:3.11-slim-bookworm@sha256:9358444059ed78e2975ada2c189f1c1a3144a5dab6f35bff8c981afb38946634 AS builder

WORKDIR /build

# System build tools (removed after this stage)
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        git \
    && rm -rf /var/lib/apt/lists/*

# Create an isolated virtualenv
RUN python -m venv /opt/venv
ENV MODEL_PATH=models/phase4_pipeline.joblib

COPY requirements.txt requirements-api.txt requirements-api.lock* ./

# Install API-only runtime dependencies from the frozen lockfile.
# requirements-api.lock is generated by:
#   pip-compile requirements-api.txt -o requirements-api.lock
# requirements-api.txt (loose pins) is kept for human readability only.
RUN /opt/venv/bin/pip install --upgrade pip \
    && if [ -f requirements-api.lock ]; then \
         echo "Using frozen lockfile requirements-api.lock"; \
         /opt/venv/bin/pip install --no-cache-dir -r requirements-api.lock; \
       else \
         echo "WARNING: no lockfile found — using loose pins from requirements-api.txt"; \
         /opt/venv/bin/pip install --no-cache-dir -r requirements-api.txt; \
       fi


# ----------------------------------------------------------------------------
# Stage 2 — API runtime image  (default)
# ----------------------------------------------------------------------------
FROM python:${PYTHON_VERSION}-slim AS api

LABEL maintainer="monzia-moodie" \
      description="Genomic Variant Pathogenicity API — Phase 2 (AUROC 0.9847)" \
      org.opencontainers.image.source="https://github.com/monzia-moodie/genomic-variant-classifier"

# Copy virtualenv from builder
COPY --from=builder /opt/venv /opt/venv
ENV MODEL_PATH=models/phase4_pipeline.joblib

RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Application source — only what inference needs
COPY src/api/          src/api/
COPY src/models/       src/models/
COPY src/utils/        src/utils/
COPY src/__init__.py   src/__init__.py

# Model artefact placeholder — override at runtime via bind-mount or COPY
RUN mkdir -p models

# Non-root user for security
RUN adduser --disabled-password --gecos "" appuser \
    && chown -R appuser:appuser /app
USER appuser

# Default environment
ENV MODEL_PATH=/app/models/phase4_pipeline.joblib \
    PATH=/opt/venv/bin:$PATH \
    GENE_SUMMARY_PATH=/app/data/processed/gene_summary.parquet \
    LOG_LEVEL=INFO \
    WORKERS=2 \
    PORT=8000

EXPOSE ${PORT}

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
    CMD python -c \
        "import urllib.request, sys; \
         r = urllib.request.urlopen('http://localhost:${PORT}/health', timeout=4); \
         sys.exit(0 if r.status == 200 else 1)"

# gunicorn with uvicorn workers for async FastAPI
CMD ["sh", "-c", \
     "gunicorn src.api.main:app \
        -k uvicorn.workers.UvicornWorker \
        --bind 0.0.0.0:${PORT} \
        --workers ${WORKERS} \
        --timeout 120 \
        --log-level ${LOG_LEVEL}"]


# ----------------------------------------------------------------------------
# Stage 3 — trainer  (build with --target trainer)
# ----------------------------------------------------------------------------
FROM python:${PYTHON_VERSION}-slim AS trainer

LABEL description="Genomic Variant Classifier — training image (Phase 2)"

RUN apt-get update && apt-get install -y --no-install-recommends \
        openjdk-21-jre-headless \
        procps \
    && rm -rf /var/lib/apt/lists/*

# Re-use builder venv but install full training stack on top
COPY --from=builder /opt/venv /opt/venv
ENV MODEL_PATH=models/phase4_pipeline.joblib \
    JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

WORKDIR /app

# Full source tree for training
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

# Train with the canonical Phase 2 config
CMD ["python", "scripts/run_phase2_eval.py", \
     "--clinvar",       "data/processed/clinvar_grch38.parquet", \
     "--alphamissense", "data/external/alphamissense/AlphaMissense_hg38.tsv.gz", \
     "--gnomad",        "data/processed/gnomad_v4_exomes.parquet", \
     "--skip-nn", "--skip-svm", \
     "--min-review-tier", "2", \
     "--output",        "outputs/latest"]









